CITIES_VALUES = {
    'city_service_nikosiya': 'Никосия',
    'city_service_girne': 'Гирне',
    'city_service_phamagusta': 'Фамагуста',
    'city_service_guzel': 'Гюзельюрт',
    'city_service_iscle': 'Искеле',
}

SERVICE_OPTIONS = {
    'opt_service_SMM':  'SMM/WEB',
    'opt_service_pharmacy': 'Аптеки',
    'opt_service_studio': 'Ателье',
    'opt_service_bathhouse': 'Бани/Хамам',
    'opt_service_hospital': 'Больницы',
    'opt_service_veyp': 'Вейпы',
    'opt_service_pethospital': 'ВетКлиники',
    'opt_service_water': 'Вода/Газ',
    'opt_service_supplying': 'Грузоперевозки',
    'opt_service_child': 'Детские сады',
    'opt_service_design': 'Дизайн',
    'opt_service_orderfood': 'Еда на заказ',
    'opt_service_netcafe': 'Интернет Кафе',
    'opt_service_casino': 'Казино',
    'opt_service_smoking': 'Кальянные',
    'opt_service_karaoke': 'Караоке',
    'opt_service_cafebars': 'Кафе/Бары',
    'opt_service_cleaning': 'Клининг',
    'opt_service_pchelp': 'Компьютерная помощь',
    'opt_service_copycentre': 'Копи центр',
    'opt_service_spa': 'Красота',
    'opt_service_massage': 'Массаж',
    'opt_service_nanny': 'Няни',
    'opt_service_barbershop': 'Парикмахерские',
    'opt_service_beach': 'Пляжи',
    'opt_service_laundry': 'Прачечные',
    'opt_service_entertainment': 'Развлечения',
    'opt_service_repair': 'Ремонт',
    'opt_service_restaurant': 'Рестораны',
    'opt_service_market': 'Рынки',
    'opt_service_serviceline': 'Салон связи',
    'opt_service_selfdev': 'Саморазвитие',
    'opt_service_sport': 'Спорт',
    'opt_service_insurance': 'Страхование',
    'opt_service_supermarkets': 'Супермаркеты',
    'opt_service_TV': 'ТВ (и интернет)',
    'opt_service_mall': 'ТЦ',
    'opt_service_photo': 'Фото/Видео',
    'opt_service_flowers': 'Цветы',
    'opt_service_schools': 'Школы',
    'opt_service_tattoo': 'Тату',
    'opt_service_masknet': 'Москитные сетки',
    'opt_service_music': 'Музыкальное искусство'

}